// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPiFBtQGI4IltAo48yYXXdbBrC1YTbwd8',
    appId: '1:852831416186:web:5d4ed28a03536a74b870c3',
    messagingSenderId: '852831416186',
    projectId: 'app-public-facility-reporting',
    authDomain: 'app-public-facility-reporting.firebaseapp.com',
    storageBucket: 'app-public-facility-reporting.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMArle1hjJi0dfzcxVkOjpOI8ZQ_gxe_c',
    appId: '1:852831416186:android:3265fe20e07b4d75b870c3',
    messagingSenderId: '852831416186',
    projectId: 'app-public-facility-reporting',
    storageBucket: 'app-public-facility-reporting.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmPI-nwWX-l5BgY2j8O-AJQbI-6IqbH1Y',
    appId: '1:852831416186:ios:0666367f33bd3c1eb870c3',
    messagingSenderId: '852831416186',
    projectId: 'app-public-facility-reporting',
    storageBucket: 'app-public-facility-reporting.firebasestorage.app',
    iosBundleId: 'com.example.appPublicFacilityReport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmPI-nwWX-l5BgY2j8O-AJQbI-6IqbH1Y',
    appId: '1:852831416186:ios:0666367f33bd3c1eb870c3',
    messagingSenderId: '852831416186',
    projectId: 'app-public-facility-reporting',
    storageBucket: 'app-public-facility-reporting.firebasestorage.app',
    iosBundleId: 'com.example.appPublicFacilityReport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPiFBtQGI4IltAo48yYXXdbBrC1YTbwd8',
    appId: '1:852831416186:web:6cbbd3be685348feb870c3',
    messagingSenderId: '852831416186',
    projectId: 'app-public-facility-reporting',
    authDomain: 'app-public-facility-reporting.firebaseapp.com',
    storageBucket: 'app-public-facility-reporting.firebasestorage.app',
  );
}
